---
deployment:
  tasks:
    - export DEPLOYPATH=/home/triojmvc/cyberlyx.cloud/
    - echo "Starting deployment to $DEPLOYPATH"
    - /usr/bin/rsync -azv --exclude='.git/' ./ $DEPLOYPATH
    - echo "Deployment completed successfully!"
